---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## tabraux

This package contains auxiliary functions for package [tabr](https://github.com/leonawicz/tabr).  

While working with the package to copy music sheets (my use case being to 'translate' the bass stave in F-key to the G-key I am used to) I noticed that the `tabr::pc` function could not handle redundant white-space (but it can now) and that it toke me some time to add to the notes the octave and sharp-flat information. While I may add more functions to this auxilary package in the future, at the moment it contains the functions: 

- `expand_notes` : this copies the octave number from a previous specification and insert sharp and flat information where needed 
- `check_times` : counts the notes in each measure to allow easy checking
- `lilypond_version` : returns the version of the lilypond executable (Windows only)
- `edit_phrase` : function that edits a phrase in a 'musical phrase' or 'track' with `sub` or `gsub` 
- `phrase2` : function that allows inserting an anchor point in a phrase
- `cond_transpose` : transposes in a musical script notes below a certain note (e.g. 'e' or 'd' upwards with an octave 


